---

- name: Cisco show version example
  hosts: pe-g17-1
  gather_facts: False

  tasks:
    - name: run show version on the routers
      ios_command:
        commands: show version | incl .bin
      register: output

    - name: print output
      debug:
        var: output.stdout_lines
